'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

import sys
import os

dir_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(dir_path+'/util')

import numbers_lib

def fib(previous, next_v):	
	return((next_v, previous + next_v ))


if len(sys.argv) !=2:
	print("Usage: python " + sys.argv[0] + " max_limit")
else:
	max = int(sys.argv[1])

	previous_value = 1
	current_value = 1
	
	total = 0

	for current_value in numbers_lib.fibGenerator(max):
		if current_value % 2 == 0:
			total = total + current_value

	print(total)
